$(document).ready(function(){
	$('#show-carousel').click(function(){
		$('.center-data').toggleClass("inactive");
	});
	$('#close-carousel').click(function(){
		$('.center-data').toggleClass('inactive');
	});
	$('#my-flights').click(function(){
		$('.flight-bar').show();
		$('.main-content').css("width","80%");
		$(".flight-bar").css("width","20%");
	});
	$('#close-flight').click(function(){
		$('.flight-bar').hide();
	});
});
