$(document).ready(function(){
	$('#show-carousel').click(function(){
		$('.center-data').toggleClass("inactive");
	});
	$('.close').click(function(){
		$('.center-data').toggleClass('inactive');
	});
	$('#my-flights').click(function(){
		$('.flight-bar').show();
	});
});
